---
- name: Check systemd service status
  ansible.builtin.systemd:
    name: "oasis-{{ network }}-{{ node_type }}"
  register: service_status

- name: Display service status
  debug:
    msg: "Service oasis-{{ network }}-{{ node_type }} status: {{ service_status.status.ActiveState }}"

- name: Get node status
  command: "/home/{{ node_user }}/bin/oasis-node control status --address unix:/home/{{ node_user }}/data/internal.sock"
  register: node_status_raw
  changed_when: false
  when: service_status.status.ActiveState == 'active'

- name: Parse and display node status
  debug:
    var: node_status_raw.stdout | from_json
  when: node_status_raw.stdout is defined