---
- name: Get recommended version and seeds from documentation
  uri:
    url: "https://raw.githubusercontent.com/oasisprotocol/docs/refs/heads/main/docs/node/network/{{ network }}.md"
    return_content: yes
    status_code: 200
  register: network_doc

- name: Parse recommended version
  set_fact:
    new_target_version: "{{ (network_doc.content | regex_search('\\*\\s+\\[([0-9]+\\.[0-9]+(?:\\.[0-9]+)?)\\]', '\\1') | default([''], true) | first) }}"

- name: Parse seed peers
  set_fact:
    new_seed_peers: "{{ network_doc.content | regex_findall('[a-zA-Z0-9/+=]+@([0-9]{1,3}\\.){3}[0-9]{1,3}:[0-9]+') | sort }}"

- name: Get latest block height for checkpoint sync
  uri:
    url: "https://api.oasisscan.com/v2/{{ network }}/chain/blocks?page=1&size=1"
    return_content: yes
    status_code: 200
  register: latest_block_info

- name: Calculate trust height (~10 days ago)
  set_fact:
    trust_height_target: "{{ latest_block_info.json.data.list[0].height - 144000 }}"

- name: Get block at trust height
  uri:
    url: "https://api.oasisscan.com/v2/{{ network }}/chain/block/{{ trust_height_target }}"
    return_content: yes
    status_code: 200
  register: trust_block_info
  when: trust_height_target is defined

- name: Set new checkpoint sync facts
  set_fact:
    new_checkpoint_sync_height: "{{ trust_block_info.json.data.height }}"
    new_checkpoint_sync_hash: "{{ trust_block_info.json.data.hash }}"

- name: Check if config has changed
  set_fact:
    config_changed: >-
      {{ (new_target_version is defined and new_target_version != target_version) or
         (new_seed_peers is defined and new_seed_peers | difference(seed_peers | sort) | length > 0) or
         (new_checkpoint_sync_height is defined and new_checkpoint_sync_height != checkpoint_sync_height) or
         (new_checkpoint_sync_hash is defined and new_checkpoint_sync_hash != checkpoint_sync_hash) }}

- name: Update variables and re-render config if changed
  block:
    - name: Update target_version variable
      set_fact:
        target_version: "{{ new_target_version }}"
      when: new_target_version is defined

    - name: Update seed_peers variable
      set_fact:
        seed_peers: "{{ new_seed_peers }}"
      when: new_seed_peers is defined

    - name: Update checkpoint_sync_height variable
      set_fact:
        checkpoint_sync_height: "{{ new_checkpoint_sync_height }}"
      when: new_checkpoint_sync_height is defined

    - name: Update checkpoint_sync_hash variable
      set_fact:
        checkpoint_sync_hash: "{{ new_checkpoint_sync_hash }}"
      when: new_checkpoint_sync_hash is defined

    - name: Re-render config.yml from template
      template:
        src: config.yml.j2
        dest: "/home/{{ node_user }}/etc/config.yml"
        owner: "{{ node_user }}"
        group: "{{ node_user }}"
        mode: '0644'
      notify: restart oasis-node
  when: config_changed | default(false)